CI github actions.
ERC-BPGC/gennav_ros pull request #5
Opened 2020-09-05 14:11 UTC by Srujan-D

I have used the most starred repos of the respective formatting software. I'm not sure whether I have used them in the correct way.

2020-09-06 10:58 UTC, threewisemonkeys-as commented
```
      # Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Lint check
        run: |
          flake8 .
          black --check .
          isort --profile black -c .
```

Could you try doing something like this instead of using 3 seperate actions? Would be better since we can easily edit which version we want etc...

2020-09-06 11:00 UTC, threewisemonkeys-as commented
https://docs.github.com/en/actions/configuring-and-managing-workflows/

You can check out docs for more details

2020-09-06 11:33 UTC, Srujan-D commented
> Could you try doing something like this instead of using 3 seperate actions? Would be better since we can easily edit which version we want etc...

Yeah okay, should I make 3 different runs for flake8, isort and black, or do it in 1 run itself? There will be only 1 job in both the cases.

2020-09-06 14:03 UTC, threewisemonkeys-as commented
Yeah, that works too

2020-09-07 11:29 UTC, threewisemonkeys-as requested changes

2020-09-07 11:29 UTC, threewisemonkeys-as commented on .github/workflows/formatting.yml
> +            python-version: [3.6, 2.7]
for linting we only need 3.6

2020-09-22 16:13 UTC, threewisemonkeys-as approved these changes

2020-09-22 16:13 UTC, merged